required = [
    "github.com/gogo/googleapis/google/api",
    "github.com/gogo/protobuf/protoc-gen-gogo",
    "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
    "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
    "github.com/mwitkow/go-proto-validators/protoc-gen-govalidators",
    "github.com/rakyll/statik",
]

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false

  [[prune.project]]
    name = "github.com/gogo/googleapis"
    non-go = false

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    non-go = false

  [[prune.project]]
    name = "github.com/mwitkow/go-proto-validators"
    non-go = false

